# Generated by Django 4.0.3 on 2022-05-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPersonne', models.CharField(max_length=30)),
                ('prenomPersonne', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produitRef', models.CharField(max_length=30)),
                ('nomProduit', models.CharField(max_length=30)),
                ('dateProduction', models.DateField()),
                ('prix', models.FloatField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rabou_abdelfattah.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceCmd', models.CharField(max_length=30)),
                ('dateCmd', models.DateField()),
                ('personne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rabou_abdelfattah.personne')),
                ('produits', models.ManyToManyField(to='rabou_abdelfattah.produit')),
            ],
        ),
    ]
